# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_interface import ai_analyze_pb2 as grpc__interface_dot_ai__analyze__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_interface/ai_analyze_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiAnalyzeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AiAnalyze = channel.unary_unary(
                '/pixanalyser.AiAnalyzeService/AiAnalyze',
                request_serializer=grpc__interface_dot_ai__analyze__pb2.AiAnalyzeRequest.SerializeToString,
                response_deserializer=grpc__interface_dot_ai__analyze__pb2.AiAnalyzeResponse.FromString,
                _registered_method=True)


class AiAnalyzeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AiAnalyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiAnalyzeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AiAnalyze': grpc.unary_unary_rpc_method_handler(
                    servicer.AiAnalyze,
                    request_deserializer=grpc__interface_dot_ai__analyze__pb2.AiAnalyzeRequest.FromString,
                    response_serializer=grpc__interface_dot_ai__analyze__pb2.AiAnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pixanalyser.AiAnalyzeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pixanalyser.AiAnalyzeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiAnalyzeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AiAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pixanalyser.AiAnalyzeService/AiAnalyze',
            grpc__interface_dot_ai__analyze__pb2.AiAnalyzeRequest.SerializeToString,
            grpc__interface_dot_ai__analyze__pb2.AiAnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
