# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_analyze_cnpj.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_analyze_cnpj.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61i_analyze_cnpj.proto\x12\x0bpixanalyzer\"\xe0\x03\n\x14\x41iAnalyzeCnpjRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x18\n\x10origin_client_id\x18\x02 \x01(\x05\x12\x1d\n\x15\x64\x65stination_key_value\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x0b\n\x03key\x18\x06 \x01(\t\x12\x10\n\x08key_type\x18\x07 \x01(\t\x12\x13\n\x0binstitution\x18\x08 \x01(\t\x12\x0e\n\x06\x62ranch\x18\t \x01(\t\x12\x16\n\x0e\x61\x63\x63ount_number\x18\n \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x0b \x01(\t\x12\x12\n\nowner_type\x18\x0c \x01(\t\x12\x12\n\nowner_name\x18\r \x01(\t\x12\x0c\n\x04\x63npj\x18\x0e \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x0f \x01(\t\x12\x19\n\x11registration_date\x18\x10 \x01(\t\x12\x0e\n\x06status\x18\x11 \x01(\t\x12\x13\n\x0bstatus_date\x18\x12 \x01(\t\x12\x15\n\rshare_capital\x18\x13 \x01(\x01\x12\x13\n\x0b\x62ranch_type\x18\x14 \x01(\t\x12\x1f\n\x17\x63ommon_transfers_client\x18\x15 \x01(\x05\x12\x15\n\rall_transfers\x18\x16 \x01(\x05\"H\n\x15\x41iAnalyzeCnpjResponse\x12\x18\n\x10\x63onfidence_score\x18\x01 \x01(\x01\x12\x15\n\rfraud_reasons\x18\x02 \x03(\t2n\n\x14\x41iAnalyzeCnpjService\x12V\n\rAiAnalyzeCnpj\x12!.pixanalyzer.AiAnalyzeCnpjRequest\x1a\".pixanalyzer.AiAnalyzeCnpjResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_analyze_cnpj_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIANALYZECNPJREQUEST']._serialized_start=39
  _globals['_AIANALYZECNPJREQUEST']._serialized_end=519
  _globals['_AIANALYZECNPJRESPONSE']._serialized_start=521
  _globals['_AIANALYZECNPJRESPONSE']._serialized_end=593
  _globals['_AIANALYZECNPJSERVICE']._serialized_start=595
  _globals['_AIANALYZECNPJSERVICE']._serialized_end=705
# @@protoc_insertion_point(module_scope)
